.TH XBPS-FREEDOM 1 "September 2021" "" "General Commands Manual"
.SH NAME
xbps-freedom \- (unofficial) XBPS tool to list and count packages that respect 
your freedom
.SH SYNOPSIS
.B xbps-freedom
[\fIOPTION\fR...]
.SH DESCRIPTION
The \fBxbps-freedom\fR utility counts and displays a formatted list of packages that respect your freedom.
.SH OPTIONS
.TP
\fB-v\fR
Display the packages and their respect of the users' freedom while processing.
.TP
\fB-V\fR
Similar to \fB-v\fR with addition of the packages' license(s) listing.
.SH AUTHOR
Written by Wafelack <wafelack@riseup.net>.
.SH COYPRIGHT
Copyright \(co 2021 Wafelack
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
xbps-query(1)
